const path = require('path');
require('dotenv').config({ path: path.join(__dirname, '.env') });
require('dotenv').config();

const mongoose = require('mongoose');
const { connectDB } = require('./config/db');
const Ingredient = require('./models/Ingredient');
const Recipe = require('./models/Recipe');
const User = require('./models/User');

const ingredientData = [
  { name: 'Egg', category: 'Protein', icon: '🥚', unit: 'piece', substitutes: ['Flax Egg', 'Banana', 'Yogurt'], nutrition: { calories: 78, protein: 6, carbs: 0.6, fat: 5 } },
  { name: 'Milk', category: 'Dairy', icon: '🥛', unit: 'ml', substitutes: ['Soy Milk', 'Almond Milk', 'Coconut Milk'], nutrition: { calories: 61, protein: 3.2, carbs: 4.8, fat: 3.3 } },
  { name: 'Cheese', category: 'Dairy', icon: '🧀', unit: 'gram', substitutes: ['Paneer', 'Tofu', 'Yogurt'], nutrition: { calories: 402, protein: 25, carbs: 1.3, fat: 33 } },
  { name: 'Tomato', category: 'Vegetables', icon: '🍅', unit: 'piece', substitutes: ['Tomato Paste', 'Capsicum', 'Sun-dried Tomato'], nutrition: { calories: 18, protein: 0.9, carbs: 3.9, fat: 0.2 } },
  { name: 'Onion', category: 'Vegetables', icon: '🧅', unit: 'piece', substitutes: ['Shallots', 'Leek', 'Spring Onion'], nutrition: { calories: 40, protein: 1.1, carbs: 9.3, fat: 0.1 } },
  { name: 'Garlic', category: 'Vegetables', icon: '🧄', unit: 'clove', substitutes: ['Garlic Powder', 'Ginger', 'Shallots'], nutrition: { calories: 149, protein: 6.4, carbs: 33, fat: 0.5 } },
  { name: 'Chicken', category: 'Protein', icon: '🍗', unit: 'gram', substitutes: ['Tofu', 'Paneer', 'Mushroom'], nutrition: { calories: 239, protein: 27, carbs: 0, fat: 14 } },
  { name: 'Rice', category: 'Grains', icon: '🍚', unit: 'cup', substitutes: ['Quinoa', 'Pasta', 'Cauliflower Rice'], nutrition: { calories: 130, protein: 2.7, carbs: 28, fat: 0.3 } },
  { name: 'Pasta', category: 'Grains', icon: '🍝', unit: 'gram', substitutes: ['Rice', 'Noodles', 'Zucchini Noodles'], nutrition: { calories: 131, protein: 5, carbs: 25, fat: 1.1 } },
  { name: 'Potato', category: 'Vegetables', icon: '🥔', unit: 'piece', substitutes: ['Sweet Potato', 'Cauliflower', 'Turnip'], nutrition: { calories: 87, protein: 1.9, carbs: 20, fat: 0.1 } },
  { name: 'Carrot', category: 'Vegetables', icon: '🥕', unit: 'piece', substitutes: ['Pumpkin', 'Sweet Potato', 'Parsnip'], nutrition: { calories: 41, protein: 0.9, carbs: 10, fat: 0.2 } },
  { name: 'Spinach', category: 'Vegetables', icon: '🥬', unit: 'cup', substitutes: ['Kale', 'Swiss Chard', 'Coriander'], nutrition: { calories: 23, protein: 2.9, carbs: 3.6, fat: 0.4 } },
  { name: 'Butter', category: 'Dairy', icon: '🧈', unit: 'gram', substitutes: ['Olive Oil', 'Ghee', 'Coconut Oil'], nutrition: { calories: 717, protein: 0.9, carbs: 0.1, fat: 81 } },
  { name: 'Olive Oil', category: 'Pantry', icon: '🫒', unit: 'tbsp', substitutes: ['Vegetable Oil', 'Butter', 'Coconut Oil'], nutrition: { calories: 884, protein: 0, carbs: 0, fat: 100 } },
  { name: 'Salt', category: 'Spices', icon: '🧂', unit: 'tsp', substitutes: ['Soy Sauce', 'Sea Salt', 'Himalayan Salt'], nutrition: { calories: 0, protein: 0, carbs: 0, fat: 0 } },
  { name: 'Pepper', category: 'Spices', icon: '🌶️', unit: 'tsp', substitutes: ['Chilli Flakes', 'Paprika', 'White Pepper'], nutrition: { calories: 251, protein: 10, carbs: 64, fat: 3.3 } },
  { name: 'Bread', category: 'Grains', icon: '🍞', unit: 'slice', substitutes: ['Tortilla', 'Wrap', 'Rice Cakes'], nutrition: { calories: 265, protein: 9, carbs: 49, fat: 3.2 } },
  { name: 'Flour', category: 'Grains', icon: '🌾', unit: 'cup', substitutes: ['Almond Flour', 'Rice Flour', 'Oat Flour'], nutrition: { calories: 364, protein: 10, carbs: 76, fat: 1 } },
  { name: 'Sugar', category: 'Pantry', icon: '🍬', unit: 'tsp', substitutes: ['Honey', 'Maple Syrup', 'Jaggery'], nutrition: { calories: 387, protein: 0, carbs: 100, fat: 0 } },
  { name: 'Lemon', category: 'Fruits', icon: '🍋', unit: 'piece', substitutes: ['Vinegar', 'Lime', 'Yogurt'], nutrition: { calories: 29, protein: 1.1, carbs: 9.3, fat: 0.3 } },
  { name: 'Capsicum', category: 'Vegetables', icon: '🫑', unit: 'piece', substitutes: ['Carrot', 'Zucchini', 'Tomato'], nutrition: { calories: 31, protein: 1, carbs: 6, fat: 0.3 } },
  { name: 'Green Peas', category: 'Vegetables', icon: '🫛', unit: 'cup', substitutes: ['Edamame', 'Corn', 'Broad Beans'], nutrition: { calories: 81, protein: 5.4, carbs: 14, fat: 0.4 } },
  { name: 'Paneer', category: 'Dairy', icon: '🧊', unit: 'gram', substitutes: ['Tofu', 'Chicken', 'Cheese'], nutrition: { calories: 321, protein: 21, carbs: 1.2, fat: 25 } },
  { name: 'Yogurt', category: 'Dairy', icon: '🥣', unit: 'cup', substitutes: ['Sour Cream', 'Buttermilk', 'Milk'], nutrition: { calories: 59, protein: 10, carbs: 3.6, fat: 0.4 } },
  { name: 'Ginger', category: 'Spices', icon: '🫚', unit: 'inch', substitutes: ['Garlic', 'Ginger Powder', 'Turmeric'], nutrition: { calories: 80, protein: 1.8, carbs: 18, fat: 0.8 } },
  { name: 'Coriander', category: 'Spices', icon: '🌿', unit: 'tbsp', substitutes: ['Parsley', 'Basil', 'Mint'], nutrition: { calories: 23, protein: 2.1, carbs: 3.7, fat: 0.5 } },
  { name: 'Chilli', category: 'Spices', icon: '🌶️', unit: 'piece', substitutes: ['Chilli Powder', 'Cayenne Pepper', 'Paprika'], nutrition: { calories: 40, protein: 1.9, carbs: 8.8, fat: 0.4 } },
  { name: 'Mushroom', category: 'Vegetables', icon: '🍄', unit: 'gram', substitutes: ['Eggplant', 'Tofu', 'Zucchini'], nutrition: { calories: 22, protein: 3.1, carbs: 3.3, fat: 0.3 } },
  { name: 'Corn', category: 'Vegetables', icon: '🌽', unit: 'cup', substitutes: ['Peas', 'Edamame', 'Chickpeas'], nutrition: { calories: 86, protein: 3.2, carbs: 19, fat: 1.2 } },
  { name: 'Tofu', category: 'Protein', icon: '🫘', unit: 'gram', substitutes: ['Paneer', 'Chicken', 'Mushroom'], nutrition: { calories: 76, protein: 8, carbs: 1.9, fat: 4.8 } },
  { name: 'Turmeric', category: 'Spices', icon: '🟡', unit: 'tsp', substitutes: ['Ginger', 'Curry Powder', 'Saffron'], nutrition: { calories: 24, protein: 0.5, carbs: 4.4, fat: 0.7 } },
  { name: 'Cumin', category: 'Spices', icon: '🌱', unit: 'tsp', substitutes: ['Coriander', 'Caraway', 'Fennel'], nutrition: { calories: 22, protein: 1, carbs: 2.6, fat: 1.3 } },
  { name: 'Garam Masala', category: 'Spices', icon: '🥘', unit: 'tsp', substitutes: ['Curry Powder', 'Allspice', 'Cumin & Coriander'], nutrition: { calories: 20, protein: 0.8, carbs: 3, fat: 0.8 } },
  { name: 'Mustard Seeds', category: 'Spices', icon: '🟡', unit: 'tsp', substitutes: ['Cumin Seeds', 'Horseradish', 'Wasabi'], nutrition: { calories: 15, protein: 0.7, carbs: 0.8, fat: 1 } },
  { name: 'Curry Leaves', category: 'Spices', icon: '🍃', unit: 'sprig', substitutes: ['Bay Leaves', 'Lime Zest', 'Basil'], nutrition: { calories: 5, protein: 0.3, carbs: 0.8, fat: 0.1 } },
  { name: 'Kasuri Methi', category: 'Spices', icon: '🌿', unit: 'tbsp', substitutes: ['Celery Leaves', 'Spinach', 'Coriander'], nutrition: { calories: 10, protein: 0.7, carbs: 1.5, fat: 0.2 } },
  { name: 'Ghee', category: 'Dairy', icon: '🧈', unit: 'tbsp', substitutes: ['Butter', 'Coconut Oil', 'Mustard Oil'], nutrition: { calories: 112, protein: 0, carbs: 0, fat: 12.7 } },
  { name: 'Basmati Rice', category: 'Grains', icon: '🍚', unit: 'cup', substitutes: ['Jasmine Rice', 'Brown Rice', 'Quinoa'], nutrition: { calories: 160, protein: 3, carbs: 36, fat: 0.5 } },
  { name: 'Toor Dal', category: 'Grains', icon: '🥣', unit: 'cup', substitutes: ['Moong Dal', 'Masoor Dal', 'Chana Dal'], nutrition: { calories: 198, protein: 11, carbs: 35, fat: 0.9 } },
  { name: 'Moong Dal', category: 'Grains', icon: '🥣', unit: 'cup', substitutes: ['Toor Dal', 'Masoor Dal', 'Urad Dal'], nutrition: { calories: 147, protein: 9, carbs: 26, fat: 0.5 } },
  { name: 'Black Lentils', category: 'Grains', icon: '🥣', unit: 'cup', substitutes: ['Red Kidney Beans', 'Brown Lentils', 'Moong Dal'], nutrition: { calories: 230, protein: 15, carbs: 40, fat: 1 } },
  { name: 'Chickpeas', category: 'Protein', icon: '🧆', unit: 'cup', substitutes: ['Black Beans', 'Kidney Beans', 'Paneer'], nutrition: { calories: 269, protein: 14.5, carbs: 45, fat: 4.2 } },
  { name: 'Kidney Beans', category: 'Protein', icon: '🫘', unit: 'cup', substitutes: ['Chickpeas', 'Black Beans', 'Lentils'], nutrition: { calories: 225, protein: 15, carbs: 40, fat: 0.9 } },
  { name: 'Cauliflower', category: 'Vegetables', icon: '🥦', unit: 'piece', substitutes: ['Broccoli', 'Cabbage', 'Potato'], nutrition: { calories: 25, protein: 2, carbs: 5, fat: 0.3 } },
  { name: 'Coconut Milk', category: 'Dairy', icon: '🥥', unit: 'ml', substitutes: ['Almond Milk', 'Yogurt', 'Heavy Cream'], nutrition: { calories: 230, protein: 2.3, carbs: 5.5, fat: 24 } },
  { name: 'Mint', category: 'Spices', icon: '🌱', unit: 'tbsp', substitutes: ['Coriander', 'Basil', 'Parsley'], nutrition: { calories: 5, protein: 0.3, carbs: 1, fat: 0.1 } },
  { name: 'Cardamom', category: 'Spices', icon: '🫘', unit: 'pod', substitutes: ['Cinnamon', 'Nutmeg', 'Cloves'], nutrition: { calories: 10, protein: 0.3, carbs: 2, fat: 0.2 } },
  { name: 'Cinnamon', category: 'Spices', icon: '🪵', unit: 'stick', substitutes: ['Cardamom', 'Nutmeg', 'Allspice'], nutrition: { calories: 12, protein: 0.1, carbs: 3, fat: 0.1 } },
  { name: 'Fish', category: 'Protein', icon: '🐟', unit: 'gram', substitutes: ['Prawns', 'Chicken', 'Tofu'], nutrition: { calories: 206, protein: 22, carbs: 0, fat: 12 } },
  { name: 'Tamarind', category: 'Pantry', icon: '🟤', unit: 'tbsp', substitutes: ['Lemon Juice', 'Amchur', 'Vinegar'], nutrition: { calories: 25, protein: 0.3, carbs: 6.5, fat: 0.1 } },
];

const buildRecipes = (ingMap) => [
  {
    title: 'Classic Omelette',
    description: 'A fluffy, golden omelette filled with melted cheese, fresh tomatoes, and caramelized onions. Perfect for a quick and satisfying breakfast or brunch.',
    imageUrl: 'https://images.unsplash.com/photo-1612240498936-65f5101365d2?w=800&q=80',
    prepTimeMinutes: 5, cookTimeMinutes: 10, difficulty: 'Easy',
    cuisine: 'French', mealType: 'Breakfast', servings: 2,
    dietaryTags: ['vegetarian'],
    nutrition: { calories: 320, protein: 22, carbs: 8, fat: 22, fiber: 1 },
    popularity: 95,
    ingredients: [
      { ingredientId: ingMap['egg'], amount: '3 eggs', isOptional: false, importance: 3 },
      { ingredientId: ingMap['cheese'], amount: '50g shredded', isOptional: false, importance: 2 },
      { ingredientId: ingMap['butter'], amount: '1 tbsp', isOptional: false, importance: 2 },
      { ingredientId: ingMap['onion'], amount: '½ onion, diced', isOptional: false, importance: 1.5 },
      { ingredientId: ingMap['tomato'], amount: '1 tomato, chopped', isOptional: true, importance: 1.5 },
      { ingredientId: ingMap['salt'], amount: 'to taste', isOptional: false, importance: 1 },
      { ingredientId: ingMap['pepper'], amount: 'to taste', isOptional: true, importance: 1 },
    ],
    instructions: [
      { step: 1, description: 'Crack eggs into a bowl, season with salt and pepper, and whisk until smooth.' },
      { step: 2, description: 'Melt butter in a non-stick pan over medium heat.' },
      { step: 3, description: 'Sauté diced onion for 2 minutes until soft.' },
      { step: 4, description: 'Pour in the egg mixture. When edges start to set, add cheese and tomato.' },
      { step: 5, description: 'Fold the omelette in half and cook for 1 more minute. Serve hot.' },
    ],
  },
  {
    title: 'Vegetable Fried Rice',
    description: 'Vibrant fried rice loaded with colorful vegetables, scrambled egg, and aromatic garlic. A wholesome one-pan meal ready in under 20 minutes.',
    imageUrl: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=800&q=80',
    prepTimeMinutes: 10, cookTimeMinutes: 15, difficulty: 'Easy',
    cuisine: 'Chinese', mealType: 'Lunch', servings: 3,
    dietaryTags: ['vegetarian'],
    nutrition: { calories: 380, protein: 12, carbs: 62, fat: 10, fiber: 4 },
    popularity: 88,
    ingredients: [
      { ingredientId: ingMap['rice'], amount: '2 cups cooked', isOptional: false, importance: 3 },
      { ingredientId: ingMap['egg'], amount: '2 eggs', isOptional: true, importance: 2 },
      { ingredientId: ingMap['carrot'], amount: '1 carrot, diced', isOptional: false, importance: 2 },
      { ingredientId: ingMap['capsicum'], amount: '1 capsicum, diced', isOptional: false, importance: 2 },
      { ingredientId: ingMap['green peas'], amount: '½ cup', isOptional: true, importance: 1.5 },
      { ingredientId: ingMap['onion'], amount: '1 onion, sliced', isOptional: false, importance: 2 },
      { ingredientId: ingMap['garlic'], amount: '3 cloves, minced', isOptional: false, importance: 2 },
      { ingredientId: ingMap['olive oil'], amount: '2 tbsp', isOptional: false, importance: 1.5 },
      { ingredientId: ingMap['salt'], amount: 'to taste', isOptional: false, importance: 1 },
      { ingredientId: ingMap['pepper'], amount: 'to taste', isOptional: true, importance: 1 },
    ],
    instructions: [
      { step: 1, description: 'Heat oil in a wok or large pan over high heat.' },
      { step: 2, description: 'Sauté garlic and onion for 1 minute until fragrant.' },
      { step: 3, description: 'Add carrots and capsicum, stir-fry for 3 minutes.' },
      { step: 4, description: 'Push vegetables to the side, scramble the eggs in the center.' },
      { step: 5, description: 'Add cooked rice and green peas, toss everything together.' },
      { step: 6, description: 'Season with salt and pepper. Serve hot.' },
    ],
  },
  {
    title: 'Chicken Fried Rice',
    description: 'Restaurant-style chicken fried rice with tender marinated chicken, aromatic ginger, and smoky wok-tossed rice. Better than takeout!',
    imageUrl: 'https://images.unsplash.com/photo-1596560548464-f010549b84d7?w=800&q=80',
    prepTimeMinutes: 15, cookTimeMinutes: 20, difficulty: 'Medium',
    cuisine: 'Chinese', mealType: 'Dinner', servings: 4,
    dietaryTags: ['non-vegetarian'],
    nutrition: { calories: 450, protein: 28, carbs: 58, fat: 12, fiber: 2 },
    popularity: 90,
    ingredients: [
      { ingredientId: ingMap['rice'], amount: '2 cups cooked', isOptional: false, importance: 3 },
      { ingredientId: ingMap['chicken'], amount: '300g, cubed', isOptional: false, importance: 3 },
      { ingredientId: ingMap['egg'], amount: '2 eggs', isOptional: true, importance: 2 },
      { ingredientId: ingMap['onion'], amount: '1 onion, sliced', isOptional: false, importance: 2 },
      { ingredientId: ingMap['garlic'], amount: '4 cloves, minced', isOptional: false, importance: 2 },
      { ingredientId: ingMap['ginger'], amount: '1 inch piece', isOptional: true, importance: 1.5 },
      { ingredientId: ingMap['capsicum'], amount: '1 capsicum, diced', isOptional: true, importance: 1.5 },
      { ingredientId: ingMap['olive oil'], amount: '2 tbsp', isOptional: false, importance: 1.5 },
      { ingredientId: ingMap['salt'], amount: 'to taste', isOptional: false, importance: 1 },
      { ingredientId: ingMap['pepper'], amount: 'to taste', isOptional: true, importance: 1 },
    ],
    instructions: [
      { step: 1, description: 'Marinate chicken with salt, pepper, and half the garlic for 10 minutes.' },
      { step: 2, description: 'Heat oil in wok, cook chicken until golden. Set aside.' },
      { step: 3, description: 'In same wok, sauté garlic, ginger, and onion.' },
      { step: 4, description: 'Scramble eggs, then add rice and vegetables.' },
      { step: 5, description: 'Return chicken to wok, toss everything. Season and serve.' },
    ],
  },
  {
    title: 'Pasta Carbonara',
    description: 'A silky, rich Italian classic made with eggs, aged cheese, and black pepper. No cream needed — the magic is in the egg and cheese emulsion.',
    imageUrl: 'https://images.unsplash.com/photo-1612874742237-6526221588e3?w=800&q=80',
    prepTimeMinutes: 10, cookTimeMinutes: 15, difficulty: 'Medium',
    cuisine: 'Italian', mealType: 'Dinner', servings: 2,
    dietaryTags: ['vegetarian'],
    nutrition: { calories: 520, protein: 24, carbs: 62, fat: 20, fiber: 2 },
    popularity: 85,
    ingredients: [
      { ingredientId: ingMap['pasta'], amount: '200g spaghetti', isOptional: false, importance: 3 },
      { ingredientId: ingMap['egg'], amount: '3 eggs (+ 1 yolk)', isOptional: false, importance: 3 },
      { ingredientId: ingMap['cheese'], amount: '80g Parmesan/Pecorino', isOptional: false, importance: 2.5 },
      { ingredientId: ingMap['butter'], amount: '1 tbsp', isOptional: false, importance: 2 },
      { ingredientId: ingMap['garlic'], amount: '2 cloves', isOptional: true, importance: 1.5 },
      { ingredientId: ingMap['pepper'], amount: '1 tsp freshly ground', isOptional: false, importance: 1.5 },
      { ingredientId: ingMap['salt'], amount: 'to taste', isOptional: false, importance: 1 },
    ],
    instructions: [
      { step: 1, description: 'Cook pasta in salted boiling water until al dente. Reserve 1 cup pasta water.' },
      { step: 2, description: 'Whisk eggs, egg yolk, and cheese together in a bowl.' },
      { step: 3, description: 'Sauté garlic in butter, then remove from heat.' },
      { step: 4, description: 'Add hot pasta to the pan. Pour egg mixture over, tossing quickly.' },
      { step: 5, description: 'Add pasta water as needed for creaminess. Season generously with black pepper.' },
    ],
  },
  {
    title: 'Tomato Pasta',
    description: 'A vibrant Italian tomato pasta with garlic-infused olive oil sauce, fresh tomatoes, and a sprinkle of cheese. Simple, delicious, and ready in 20 minutes.',
    imageUrl: 'https://images.unsplash.com/photo-1555949258-eb67b1ef0ceb?w=800&q=80',
    prepTimeMinutes: 5, cookTimeMinutes: 20, difficulty: 'Easy',
    cuisine: 'Italian', mealType: 'Dinner', servings: 2,
    dietaryTags: ['vegetarian'],
    nutrition: { calories: 420, protein: 14, carbs: 68, fat: 11, fiber: 5 },
    popularity: 78,
    ingredients: [
      { ingredientId: ingMap['pasta'], amount: '200g', isOptional: false, importance: 3 },
      { ingredientId: ingMap['tomato'], amount: '4 tomatoes, chopped', isOptional: false, importance: 3 },
      { ingredientId: ingMap['garlic'], amount: '4 cloves, minced', isOptional: false, importance: 2 },
      { ingredientId: ingMap['onion'], amount: '1 onion, diced', isOptional: false, importance: 2 },
      { ingredientId: ingMap['olive oil'], amount: '3 tbsp', isOptional: false, importance: 2 },
      { ingredientId: ingMap['cheese'], amount: '30g grated', isOptional: true, importance: 1.5 },
      { ingredientId: ingMap['salt'], amount: 'to taste', isOptional: false, importance: 1 },
      { ingredientId: ingMap['pepper'], amount: 'to taste', isOptional: true, importance: 1 },
    ],
    instructions: [
      { step: 1, description: 'Cook pasta in salted boiling water until al dente.' },
      { step: 2, description: 'Heat olive oil, sauté garlic and onion until golden.' },
      { step: 3, description: 'Add tomatoes, cook for 10 minutes until sauce forms.' },
      { step: 4, description: 'Toss pasta with sauce. Top with cheese and serve.' },
    ],
  },
  {
    title: 'Tomato Soup',
    description: 'A warming, velvety tomato soup with a touch of cream, perfect for chilly days. Pairs beautifully with crusty garlic bread.',
    imageUrl: 'https://images.unsplash.com/photo-1547592180-85f173990554?w=800&q=80',
    prepTimeMinutes: 10, cookTimeMinutes: 25, difficulty: 'Easy',
    cuisine: 'American', mealType: 'Lunch', servings: 4,
    dietaryTags: ['vegetarian'],
    nutrition: { calories: 180, protein: 4, carbs: 24, fat: 9, fiber: 4 },
    popularity: 72,
    ingredients: [
      { ingredientId: ingMap['tomato'], amount: '6 tomatoes, halved', isOptional: false, importance: 3 },
      { ingredientId: ingMap['onion'], amount: '1 onion, quartered', isOptional: false, importance: 2 },
      { ingredientId: ingMap['garlic'], amount: '4 cloves', isOptional: false, importance: 2 },
      { ingredientId: ingMap['butter'], amount: '2 tbsp', isOptional: false, importance: 1.5 },
      { ingredientId: ingMap['milk'], amount: '½ cup', isOptional: true, importance: 1.5 },
      { ingredientId: ingMap['salt'], amount: 'to taste', isOptional: false, importance: 1 },
      { ingredientId: ingMap['pepper'], amount: 'to taste', isOptional: true, importance: 1 },
    ],
    instructions: [
      { step: 1, description: 'Roast tomatoes, onion, and garlic at 200°C for 20 minutes.' },
      { step: 2, description: 'Blend roasted vegetables until smooth.' },
      { step: 3, description: 'Pour into pot, add butter and milk. Simmer 5 minutes.' },
      { step: 4, description: 'Season with salt and pepper. Serve hot with crusty bread.' },
    ],
  },
  {
    title: 'Garlic Butter Chicken',
    description: 'Succulent pan-seared chicken bathed in golden garlic butter with a squeeze of lemon. An impressive yet easy dinner that feels restaurant-worthy.',
    imageUrl: 'https://images.unsplash.com/photo-1598103442097-8b74394b95c3?w=800&q=80',
    prepTimeMinutes: 10, cookTimeMinutes: 20, difficulty: 'Medium',
    cuisine: 'American', mealType: 'Dinner', servings: 2,
    dietaryTags: ['non-vegetarian', 'gluten-free'],
    nutrition: { calories: 480, protein: 42, carbs: 5, fat: 32, fiber: 0 },
    popularity: 92,
    ingredients: [
      { ingredientId: ingMap['chicken'], amount: '400g breast/thigh', isOptional: false, importance: 3 },
      { ingredientId: ingMap['garlic'], amount: '6 cloves, minced', isOptional: false, importance: 3 },
      { ingredientId: ingMap['butter'], amount: '3 tbsp', isOptional: false, importance: 2.5 },
      { ingredientId: ingMap['lemon'], amount: '1 lemon', isOptional: true, importance: 1.5 },
      { ingredientId: ingMap['coriander'], amount: '2 tbsp fresh', isOptional: true, importance: 1 },
      { ingredientId: ingMap['salt'], amount: 'to taste', isOptional: false, importance: 1 },
      { ingredientId: ingMap['pepper'], amount: 'to taste', isOptional: true, importance: 1 },
    ],
    instructions: [
      { step: 1, description: 'Season chicken with salt and pepper.' },
      { step: 2, description: 'Melt 1 tbsp butter in skillet over high heat. Sear chicken 5 min per side until golden.' },
      { step: 3, description: 'Reduce heat, add remaining butter and garlic. Baste chicken for 3 minutes.' },
      { step: 4, description: 'Squeeze lemon juice over chicken. Garnish with coriander and serve.' },
    ],
  },
  {
    title: 'Vegetable Pasta',
    description: 'A garden-fresh pasta loaded with colorful vegetables, spinach, and a light garlic olive oil sauce. Healthy, vibrant, and ready in 25 minutes.',
    imageUrl: 'https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=800&q=80',
    prepTimeMinutes: 10, cookTimeMinutes: 20, difficulty: 'Easy',
    cuisine: 'Italian', mealType: 'Dinner', servings: 3,
    dietaryTags: ['vegetarian', 'vegan'],
    nutrition: { calories: 380, protein: 12, carbs: 66, fat: 9, fiber: 6 },
    popularity: 76,
    ingredients: [
      { ingredientId: ingMap['pasta'], amount: '250g', isOptional: false, importance: 3 },
      { ingredientId: ingMap['tomato'], amount: '2 tomatoes', isOptional: false, importance: 2 },
      { ingredientId: ingMap['capsicum'], amount: '1 capsicum', isOptional: false, importance: 2 },
      { ingredientId: ingMap['spinach'], amount: '2 cups', isOptional: true, importance: 1.5 },
      { ingredientId: ingMap['onion'], amount: '1 onion', isOptional: false, importance: 2 },
      { ingredientId: ingMap['garlic'], amount: '3 cloves', isOptional: false, importance: 2 },
      { ingredientId: ingMap['olive oil'], amount: '3 tbsp', isOptional: false, importance: 2 },
      { ingredientId: ingMap['cheese'], amount: '30g grated', isOptional: true, importance: 1.5 },
      { ingredientId: ingMap['salt'], amount: 'to taste', isOptional: false, importance: 1 },
    ],
    instructions: [
      { step: 1, description: 'Cook pasta until al dente. Reserve pasta water.' },
      { step: 2, description: 'Sauté garlic and onion in olive oil until golden.' },
      { step: 3, description: 'Add capsicum and tomatoes, cook 5 minutes.' },
      { step: 4, description: 'Toss in spinach until wilted. Add pasta and toss.' },
      { step: 5, description: 'Add a splash of pasta water, top with cheese and serve.' },
    ],
  },
  {
    title: 'Paneer Curry',
    description: 'Tender cubes of paneer simmered in a rich, spiced tomato-onion gravy. This classic North Indian curry is aromatic, creamy, and absolutely soul-warming.',
    imageUrl: 'https://images.unsplash.com/photo-1631452180539-96aca7d48617?w=800&q=80',
    prepTimeMinutes: 15, cookTimeMinutes: 25, difficulty: 'Medium',
    cuisine: 'Indian', mealType: 'Dinner', servings: 4,
    dietaryTags: ['vegetarian'],
    nutrition: { calories: 380, protein: 18, carbs: 18, fat: 26, fiber: 4 },
    popularity: 89,
    ingredients: [
      { ingredientId: ingMap['paneer'], amount: '250g, cubed', isOptional: false, importance: 3 },
      { ingredientId: ingMap['tomato'], amount: '3 tomatoes, pureed', isOptional: false, importance: 3 },
      { ingredientId: ingMap['onion'], amount: '2 onions, sliced', isOptional: false, importance: 2.5 },
      { ingredientId: ingMap['garlic'], amount: '4 cloves', isOptional: false, importance: 2 },
      { ingredientId: ingMap['ginger'], amount: '1 inch piece', isOptional: false, importance: 2 },
      { ingredientId: ingMap['yogurt'], amount: '2 tbsp', isOptional: true, importance: 1.5 },
      { ingredientId: ingMap['chilli'], amount: '1-2 green chilli', isOptional: true, importance: 1.5 },
      { ingredientId: ingMap['coriander'], amount: '2 tbsp fresh', isOptional: true, importance: 1 },
      { ingredientId: ingMap['olive oil'], amount: '2 tbsp', isOptional: false, importance: 1.5 },
      { ingredientId: ingMap['salt'], amount: 'to taste', isOptional: false, importance: 1 },
    ],
    instructions: [
      { step: 1, description: 'Heat oil, fry onions until deep golden brown.' },
      { step: 2, description: 'Add garlic and ginger paste, sauté 2 minutes.' },
      { step: 3, description: 'Add tomato puree, cook until oil separates.' },
      { step: 4, description: 'Add paneer cubes, yogurt, and chilli. Simmer 10 minutes.' },
      { step: 5, description: 'Garnish with coriander. Serve with rice or bread.' },
    ],
  },
  {
    title: 'Paneer Fried Rice',
    description: 'A fusion delight — crispy paneer cubes tossed with fragrant basmati rice, colorful capsicum, and aromatic spices. A crowd-pleaser!',
    imageUrl: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=800&q=80',
    prepTimeMinutes: 15, cookTimeMinutes: 20, difficulty: 'Medium',
    cuisine: 'Indo-Chinese', mealType: 'Lunch', servings: 3,
    dietaryTags: ['vegetarian'],
    nutrition: { calories: 420, protein: 18, carbs: 55, fat: 16, fiber: 3 },
    popularity: 80,
    ingredients: [
      { ingredientId: ingMap['rice'], amount: '2 cups cooked', isOptional: false, importance: 3 },
      { ingredientId: ingMap['paneer'], amount: '200g, cubed', isOptional: false, importance: 3 },
      { ingredientId: ingMap['capsicum'], amount: '1 capsicum', isOptional: false, importance: 2 },
      { ingredientId: ingMap['onion'], amount: '1 onion', isOptional: false, importance: 2 },
      { ingredientId: ingMap['garlic'], amount: '3 cloves', isOptional: false, importance: 1.5 },
      { ingredientId: ingMap['ginger'], amount: '½ inch piece', isOptional: true, importance: 1.5 },
      { ingredientId: ingMap['olive oil'], amount: '2 tbsp', isOptional: false, importance: 1.5 },
      { ingredientId: ingMap['salt'], amount: 'to taste', isOptional: false, importance: 1 },
      { ingredientId: ingMap['pepper'], amount: 'to taste', isOptional: true, importance: 1 },
    ],
    instructions: [
      { step: 1, description: 'Pan-fry paneer cubes until golden. Set aside.' },
      { step: 2, description: 'Sauté garlic, ginger, and onion in oil until fragrant.' },
      { step: 3, description: 'Add capsicum, stir-fry 3 minutes.' },
      { step: 4, description: 'Add rice and paneer, toss well. Season and serve.' },
    ],
  },
  {
    title: 'Egg Curry',
    description: 'Hard-boiled eggs simmered in a bold, spiced tomato-onion masala. This Indian egg curry is hearty, flavorful, and pairs perfectly with rice or roti.',
    imageUrl: 'https://images.unsplash.com/photo-1613844237701-8f3664fc2eff?w=800&q=80',
    prepTimeMinutes: 10, cookTimeMinutes: 25, difficulty: 'Medium',
    cuisine: 'Indian', mealType: 'Dinner', servings: 3,
    dietaryTags: ['non-vegetarian'],
    nutrition: { calories: 280, protein: 18, carbs: 16, fat: 17, fiber: 3 },
    popularity: 82,
    ingredients: [
      { ingredientId: ingMap['egg'], amount: '6 eggs, hard-boiled', isOptional: false, importance: 3 },
      { ingredientId: ingMap['tomato'], amount: '3 tomatoes, pureed', isOptional: false, importance: 3 },
      { ingredientId: ingMap['onion'], amount: '2 onions, finely chopped', isOptional: false, importance: 2.5 },
      { ingredientId: ingMap['garlic'], amount: '4 cloves, minced', isOptional: false, importance: 2 },
      { ingredientId: ingMap['ginger'], amount: '1 inch piece', isOptional: false, importance: 2 },
      { ingredientId: ingMap['chilli'], amount: '1-2 green chilli', isOptional: true, importance: 1.5 },
      { ingredientId: ingMap['coriander'], amount: '2 tbsp fresh', isOptional: true, importance: 1 },
      { ingredientId: ingMap['olive oil'], amount: '2 tbsp', isOptional: false, importance: 1.5 },
      { ingredientId: ingMap['salt'], amount: 'to taste', isOptional: false, importance: 1 },
    ],
    instructions: [
      { step: 1, description: 'Hard-boil eggs, peel and score with fork.' },
      { step: 2, description: 'Fry onions until golden, add garlic and ginger.' },
      { step: 3, description: 'Add tomato puree and chilli, cook until oil separates.' },
      { step: 4, description: 'Add eggs, coat with masala. Simmer 10 minutes.' },
      { step: 5, description: 'Garnish with coriander. Serve with rice.' },
    ],
  },
  {
    title: 'Cheese & Veggie Sandwich',
    description: 'A toasted sandwich packed with fresh vegetables, melted cheese, and a golden butter crust. Quick, satisfying, and endlessly customizable.',
    imageUrl: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=800&q=80',
    prepTimeMinutes: 5, cookTimeMinutes: 5, difficulty: 'Easy',
    cuisine: 'American', mealType: 'Snack', servings: 1,
    dietaryTags: ['vegetarian'],
    nutrition: { calories: 340, protein: 14, carbs: 38, fat: 15, fiber: 3 },
    popularity: 70,
    ingredients: [
      { ingredientId: ingMap['bread'], amount: '2 slices', isOptional: false, importance: 3 },
      { ingredientId: ingMap['cheese'], amount: '40g, sliced', isOptional: true, importance: 2 },
      { ingredientId: ingMap['tomato'], amount: '1 tomato, sliced', isOptional: false, importance: 2 },
      { ingredientId: ingMap['butter'], amount: '1 tbsp', isOptional: false, importance: 1.5 },
      { ingredientId: ingMap['onion'], amount: '½ onion, sliced', isOptional: true, importance: 1.5 },
      { ingredientId: ingMap['capsicum'], amount: '¼ capsicum', isOptional: true, importance: 1.5 },
      { ingredientId: ingMap['salt'], amount: 'to taste', isOptional: false, importance: 1 },
    ],
    instructions: [
      { step: 1, description: 'Butter one side of each bread slice.' },
      { step: 2, description: 'Layer tomato, onion, capsicum, and cheese on unbuttered side.' },
      { step: 3, description: 'Grill in pan until golden and cheese melts. Serve hot.' },
    ],
  },
  {
    title: 'Garlic Bread',
    description: 'Crispy on the outside, soft on the inside — this classic garlic bread with herb butter is the perfect side dish or snack. Ready in just 10 minutes!',
    imageUrl: 'https://images.unsplash.com/photo-1573140247632-f8fd74997d5c?w=800&q=80',
    prepTimeMinutes: 5, cookTimeMinutes: 10, difficulty: 'Easy',
    cuisine: 'Italian', mealType: 'Snack', servings: 2,
    dietaryTags: ['vegetarian'],
    nutrition: { calories: 280, protein: 6, carbs: 32, fat: 15, fiber: 1 },
    popularity: 75,
    ingredients: [
      { ingredientId: ingMap['bread'], amount: '1 baguette or 4 slices', isOptional: false, importance: 3 },
      { ingredientId: ingMap['garlic'], amount: '4 cloves, minced', isOptional: false, importance: 3 },
      { ingredientId: ingMap['butter'], amount: '50g softened', isOptional: false, importance: 2.5 },
      { ingredientId: ingMap['coriander'], amount: '1 tbsp fresh', isOptional: true, importance: 1 },
      { ingredientId: ingMap['salt'], amount: 'pinch', isOptional: true, importance: 0.5 },
    ],
    instructions: [
      { step: 1, description: 'Mix softened butter with garlic, coriander, and salt.' },
      { step: 2, description: 'Spread garlic butter generously on bread slices.' },
      { step: 3, description: 'Bake at 180°C for 8-10 minutes until golden and crispy.' },
    ],
  },
  {
    title: 'Fluffy Pancakes',
    description: 'Light, airy pancakes with a golden exterior and pillowy soft interior. Stack them high and serve with honey or fresh fruit for a weekend breakfast treat.',
    imageUrl: 'https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=800&q=80',
    prepTimeMinutes: 10, cookTimeMinutes: 15, difficulty: 'Easy',
    cuisine: 'American', mealType: 'Breakfast', servings: 4,
    dietaryTags: ['vegetarian'],
    nutrition: { calories: 320, protein: 9, carbs: 48, fat: 11, fiber: 1 },
    popularity: 88,
    ingredients: [
      { ingredientId: ingMap['flour'], amount: '1½ cups', isOptional: false, importance: 3 },
      { ingredientId: ingMap['egg'], amount: '2 eggs', isOptional: false, importance: 2.5 },
      { ingredientId: ingMap['milk'], amount: '1 cup', isOptional: false, importance: 2.5 },
      { ingredientId: ingMap['butter'], amount: '2 tbsp melted', isOptional: false, importance: 2 },
      { ingredientId: ingMap['sugar'], amount: '2 tbsp', isOptional: false, importance: 2 },
      { ingredientId: ingMap['salt'], amount: 'pinch', isOptional: true, importance: 0.5 },
    ],
    instructions: [
      { step: 1, description: 'Mix flour, sugar, and salt. Whisk in eggs, milk, and melted butter until smooth.' },
      { step: 2, description: 'Heat a non-stick pan over medium heat, lightly grease.' },
      { step: 3, description: 'Pour ¼ cup batter per pancake. Cook until bubbles form, then flip.' },
      { step: 4, description: 'Cook 1 minute more until golden. Serve with honey or fruit.' },
    ],
  },
  {
    title: 'French Toast',
    description: 'Thick bread slices soaked in a vanilla-egg custard and pan-fried to golden perfection. Dust with sugar for an indulgent morning treat.',
    imageUrl: 'https://images.unsplash.com/photo-1484723091739-30a097e8f929?w=800&q=80',
    prepTimeMinutes: 5, cookTimeMinutes: 10, difficulty: 'Easy',
    cuisine: 'French', mealType: 'Breakfast', servings: 2,
    dietaryTags: ['vegetarian'],
    nutrition: { calories: 380, protein: 14, carbs: 46, fat: 17, fiber: 2 },
    popularity: 84,
    ingredients: [
      { ingredientId: ingMap['bread'], amount: '4 thick slices', isOptional: false, importance: 3 },
      { ingredientId: ingMap['egg'], amount: '3 eggs', isOptional: false, importance: 3 },
      { ingredientId: ingMap['milk'], amount: '½ cup', isOptional: false, importance: 2 },
      { ingredientId: ingMap['butter'], amount: '2 tbsp', isOptional: false, importance: 2 },
      { ingredientId: ingMap['sugar'], amount: '2 tbsp for dusting', isOptional: true, importance: 1.5 },
      { ingredientId: ingMap['salt'], amount: 'pinch', isOptional: true, importance: 0.5 },
    ],
    instructions: [
      { step: 1, description: 'Whisk eggs, milk, and a pinch of salt in a shallow bowl.' },
      { step: 2, description: 'Dip bread slices in egg mixture, coating both sides.' },
      { step: 3, description: 'Fry in butter over medium heat until golden on each side.' },
      { step: 4, description: 'Dust with sugar and serve immediately.' },
    ],
  },
  {
    title: 'Mushroom Pasta',
    description: 'Earthy mushrooms sautéed in garlic butter tossed with al dente pasta. A simple yet deeply satisfying Italian pasta dish with umami richness.',
    imageUrl: 'https://images.unsplash.com/photo-1473093295043-cdd812d0e601?w=800&q=80',
    prepTimeMinutes: 10, cookTimeMinutes: 20, difficulty: 'Easy',
    cuisine: 'Italian', mealType: 'Dinner', servings: 2,
    dietaryTags: ['vegetarian'],
    nutrition: { calories: 440, protein: 16, carbs: 58, fat: 17, fiber: 5 },
    popularity: 83,
    ingredients: [
      { ingredientId: ingMap['pasta'], amount: '200g', isOptional: false, importance: 3 },
      { ingredientId: ingMap['mushroom'], amount: '250g, sliced', isOptional: false, importance: 3 },
      { ingredientId: ingMap['garlic'], amount: '4 cloves, minced', isOptional: false, importance: 2 },
      { ingredientId: ingMap['butter'], amount: '2 tbsp', isOptional: false, importance: 2 },
      { ingredientId: ingMap['olive oil'], amount: '2 tbsp', isOptional: false, importance: 1.5 },
      { ingredientId: ingMap['cheese'], amount: '30g Parmesan', isOptional: true, importance: 1.5 },
      { ingredientId: ingMap['salt'], amount: 'to taste', isOptional: false, importance: 1 },
      { ingredientId: ingMap['pepper'], amount: 'to taste', isOptional: true, importance: 1 },
    ],
    instructions: [
      { step: 1, description: 'Cook pasta until al dente. Reserve pasta water.' },
      { step: 2, description: 'Heat butter and olive oil, sauté garlic 1 minute.' },
      { step: 3, description: 'Add mushrooms, cook until golden and liquid evaporates.' },
      { step: 4, description: 'Toss mushrooms with pasta and a splash of pasta water. Top with cheese.' },
    ],
  },
  {
    title: 'Chicken Pasta',
    description: 'Juicy grilled chicken pieces tossed with pasta in a garlicky tomato sauce. A complete, protein-packed meal that comes together in under 30 minutes.',
    imageUrl: 'https://images.unsplash.com/photo-1563379926898-05f4575a45d8?w=800&q=80',
    prepTimeMinutes: 10, cookTimeMinutes: 25, difficulty: 'Medium',
    cuisine: 'Italian', mealType: 'Dinner', servings: 3,
    dietaryTags: ['non-vegetarian'],
    nutrition: { calories: 520, protein: 32, carbs: 58, fat: 16, fiber: 4 },
    popularity: 87,
    ingredients: [
      { ingredientId: ingMap['pasta'], amount: '250g', isOptional: false, importance: 3 },
      { ingredientId: ingMap['chicken'], amount: '300g, sliced', isOptional: false, importance: 3 },
      { ingredientId: ingMap['tomato'], amount: '2 tomatoes, chopped', isOptional: true, importance: 2 },
      { ingredientId: ingMap['garlic'], amount: '4 cloves', isOptional: false, importance: 2 },
      { ingredientId: ingMap['onion'], amount: '1 onion', isOptional: false, importance: 2 },
      { ingredientId: ingMap['olive oil'], amount: '2 tbsp', isOptional: false, importance: 1.5 },
      { ingredientId: ingMap['cheese'], amount: '40g Parmesan', isOptional: true, importance: 1.5 },
      { ingredientId: ingMap['salt'], amount: 'to taste', isOptional: false, importance: 1 },
      { ingredientId: ingMap['pepper'], amount: 'to taste', isOptional: true, importance: 1 },
    ],
    instructions: [
      { step: 1, description: 'Season and cook chicken until golden. Slice and set aside.' },
      { step: 2, description: 'Cook pasta. In same pan, sauté garlic and onion.' },
      { step: 3, description: 'Add tomatoes, cook 5 minutes. Add pasta and chicken.' },
      { step: 4, description: 'Toss well, top with Parmesan and serve.' },
    ],
  },
  {
    title: 'Classic Fried Rice',
    description: 'The ultimate comfort food — fluffy rice stir-fried with eggs, vegetables, and seasoning. A quick and satisfying meal using leftover rice.',
    imageUrl: 'https://images.unsplash.com/photo-1645696301019-35adcc18cbb3?w=800&q=80',
    prepTimeMinutes: 5, cookTimeMinutes: 15, difficulty: 'Easy',
    cuisine: 'Asian', mealType: 'Lunch', servings: 2,
    dietaryTags: ['vegetarian'],
    nutrition: { calories: 350, protein: 10, carbs: 62, fat: 9, fiber: 2 },
    popularity: 86,
    ingredients: [
      { ingredientId: ingMap['rice'], amount: '2 cups cooked', isOptional: false, importance: 3 },
      { ingredientId: ingMap['egg'], amount: '2 eggs', isOptional: false, importance: 2.5 },
      { ingredientId: ingMap['onion'], amount: '1 onion, sliced', isOptional: false, importance: 2 },
      { ingredientId: ingMap['garlic'], amount: '3 cloves, minced', isOptional: false, importance: 2 },
      { ingredientId: ingMap['carrot'], amount: '1 carrot, diced', isOptional: true, importance: 1.5 },
      { ingredientId: ingMap['olive oil'], amount: '2 tbsp', isOptional: false, importance: 1.5 },
      { ingredientId: ingMap['salt'], amount: 'to taste', isOptional: false, importance: 1 },
      { ingredientId: ingMap['pepper'], amount: 'to taste', isOptional: true, importance: 1 },
    ],
    instructions: [
      { step: 1, description: 'Heat oil in wok or large pan over high heat.' },
      { step: 2, description: 'Sauté garlic and onion until golden.' },
      { step: 3, description: 'Add carrot, stir-fry 2 minutes. Push to side.' },
      { step: 4, description: 'Scramble eggs in center, then mix with vegetables.' },
      { step: 5, description: 'Add rice, toss well. Season and serve.' },
    ],
  },
  {
    title: 'Vegetable Soup',
    description: 'A comforting, chunky vegetable soup with root vegetables, spinach, and aromatic herbs. Light, nutritious, and perfect for a cold evening.',
    imageUrl: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?w=800&q=80',
    prepTimeMinutes: 15, cookTimeMinutes: 30, difficulty: 'Easy',
    cuisine: 'International', mealType: 'Lunch', servings: 4,
    dietaryTags: ['vegetarian', 'vegan', 'gluten-free'],
    nutrition: { calories: 160, protein: 5, carbs: 32, fat: 3, fiber: 8 },
    popularity: 71,
    ingredients: [
      { ingredientId: ingMap['carrot'], amount: '2 carrots, diced', isOptional: false, importance: 2.5 },
      { ingredientId: ingMap['potato'], amount: '2 potatoes, cubed', isOptional: false, importance: 2.5 },
      { ingredientId: ingMap['onion'], amount: '1 onion, chopped', isOptional: false, importance: 2 },
      { ingredientId: ingMap['tomato'], amount: '2 tomatoes, chopped', isOptional: false, importance: 2 },
      { ingredientId: ingMap['garlic'], amount: '3 cloves', isOptional: false, importance: 2 },
      { ingredientId: ingMap['spinach'], amount: '1 cup', isOptional: true, importance: 1.5 },
      { ingredientId: ingMap['olive oil'], amount: '1 tbsp', isOptional: false, importance: 1 },
      { ingredientId: ingMap['salt'], amount: 'to taste', isOptional: false, importance: 1 },
      { ingredientId: ingMap['pepper'], amount: 'to taste', isOptional: true, importance: 1 },
    ],
    instructions: [
      { step: 1, description: 'Heat oil in large pot, sauté onion and garlic.' },
      { step: 2, description: 'Add carrots, potatoes, and tomatoes. Stir 2 minutes.' },
      { step: 3, description: 'Cover with water (4 cups), bring to boil. Simmer 20 minutes.' },
      { step: 4, description: 'Add spinach in last 2 minutes. Season and serve.' },
    ],
  },
  {
    title: 'Potato Curry',
    description: 'Soft potatoes in a fragrant, spiced tomato gravy — a simple yet deeply satisfying Indian curry. Comfort food at its finest, best served with warm roti.',
    imageUrl: 'https://images.unsplash.com/photo-1571197119733-a7e93f04c9b1?w=800&q=80',
    prepTimeMinutes: 10, cookTimeMinutes: 25, difficulty: 'Easy',
    cuisine: 'Indian', mealType: 'Dinner', servings: 3,
    dietaryTags: ['vegetarian', 'vegan', 'gluten-free'],
    nutrition: { calories: 220, protein: 5, carbs: 38, fat: 8, fiber: 5 },
    popularity: 74,
    ingredients: [
      { ingredientId: ingMap['potato'], amount: '4 potatoes, cubed', isOptional: false, importance: 3 },
      { ingredientId: ingMap['tomato'], amount: '3 tomatoes, pureed', isOptional: false, importance: 2.5 },
      { ingredientId: ingMap['onion'], amount: '2 onions, chopped', isOptional: false, importance: 2.5 },
      { ingredientId: ingMap['garlic'], amount: '4 cloves', isOptional: false, importance: 2 },
      { ingredientId: ingMap['ginger'], amount: '1 inch piece', isOptional: true, importance: 2 },
      { ingredientId: ingMap['chilli'], amount: '1-2 green chilli', isOptional: true, importance: 1.5 },
      { ingredientId: ingMap['coriander'], amount: '2 tbsp fresh', isOptional: true, importance: 1 },
      { ingredientId: ingMap['olive oil'], amount: '2 tbsp', isOptional: false, importance: 1.5 },
      { ingredientId: ingMap['salt'], amount: 'to taste', isOptional: false, importance: 1 },
    ],
    instructions: [
      { step: 1, description: 'Boil potatoes until just tender. Drain and set aside.' },
      { step: 2, description: 'Heat oil, fry onions until golden.' },
      { step: 3, description: 'Add garlic, ginger, and chilli. Sauté 2 minutes.' },
      { step: 4, description: 'Add tomato puree, cook until oil separates.' },
      { step: 5, description: 'Add potatoes, simmer 10 minutes. Garnish with coriander.' },
    ],
  },
  {
    title: 'Restaurant Style Butter Chicken (Murgh Makhani)',
    description: 'Tender marinated chicken pieces simmered in a velvety, buttery tomato-cream sauce with fragrant kasuri methi and garam masala. A timeless North Indian classic.',
    imageUrl: 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?w=800&q=80',
    prepTimeMinutes: 20, cookTimeMinutes: 30, difficulty: 'Medium',
    cuisine: 'Indian', mealType: 'Dinner', servings: 4,
    dietaryTags: ['gluten-free'],
    nutrition: { calories: 520, protein: 36, carbs: 12, fat: 34, fiber: 2 },
    popularity: 99,
    ingredients: [
      { ingredientId: ingMap['chicken'], amount: '500g boneless chicken', isOptional: false, importance: 3 },
      { ingredientId: ingMap['butter'], amount: '3 tbsp butter', isOptional: false, importance: 2.5 },
      { ingredientId: ingMap['tomato'], amount: '4 ripe tomatoes, pureed', isOptional: false, importance: 2.5 },
      { ingredientId: ingMap['garlic'], amount: '6 cloves, minced', isOptional: false, importance: 2 },
      { ingredientId: ingMap['ginger'], amount: '1 inch, grated', isOptional: false, importance: 2 },
      { ingredientId: ingMap['garam masala'], amount: '1 tsp', isOptional: false, importance: 2 },
      { ingredientId: ingMap['kasuri methi'], amount: '1 tbsp crushed', isOptional: false, importance: 2 },
      { ingredientId: ingMap['yogurt'], amount: '½ cup plain yogurt', isOptional: false, importance: 2 },
      { ingredientId: ingMap['chilli'], amount: '1 tsp Kashmiri red chilli', isOptional: false, importance: 1.5 },
      { ingredientId: ingMap['salt'], amount: 'to taste', isOptional: false, importance: 1 },
    ],
    instructions: [
      { step: 1, description: 'Marinate chicken in yogurt, garlic, ginger, chilli powder, and salt for 20 minutes.' },
      { step: 2, description: 'Pan-sear chicken in 1 tbsp butter over high heat until charred at edges.' },
      { step: 3, description: 'In the same pan, melt remaining butter and simmer pureed tomatoes for 10 minutes.' },
      { step: 4, description: 'Stir in garam masala, kasuri methi, and the cooked chicken pieces.' },
      { step: 5, description: 'Simmer on low for 8-10 minutes until thick and glossy. Serve with naan or basmati rice.' },
    ],
  },
  {
    title: 'Paneer Tikka Masala',
    description: 'Succulent cubes of paneer cooked with charred capsicum and onion in a rich, aromatic spiced gravy. A beloved vegetarian delicacy.',
    imageUrl: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=800&q=80',
    prepTimeMinutes: 15, cookTimeMinutes: 25, difficulty: 'Medium',
    cuisine: 'Indian', mealType: 'Dinner', servings: 4,
    dietaryTags: ['vegetarian', 'gluten-free'],
    nutrition: { calories: 430, protein: 22, carbs: 14, fat: 30, fiber: 3 },
    popularity: 96,
    ingredients: [
      { ingredientId: ingMap['paneer'], amount: '300g paneer cubes', isOptional: false, importance: 3 },
      { ingredientId: ingMap['capsicum'], amount: '1 green bell pepper, cubed', isOptional: false, importance: 2 },
      { ingredientId: ingMap['onion'], amount: '2 medium onions, diced', isOptional: false, importance: 2.5 },
      { ingredientId: ingMap['tomato'], amount: '3 tomatoes, pureed', isOptional: false, importance: 2.5 },
      { ingredientId: ingMap['garlic'], amount: '4 cloves', isOptional: false, importance: 1.5 },
      { ingredientId: ingMap['ginger'], amount: '1 inch piece', isOptional: false, importance: 1.5 },
      { ingredientId: ingMap['garam masala'], amount: '1 tsp', isOptional: false, importance: 2 },
      { ingredientId: ingMap['ghee'], amount: '2 tbsp ghee', isOptional: false, importance: 2 },
      { ingredientId: ingMap['kasuri methi'], amount: '1 tsp', isOptional: true, importance: 1 },
      { ingredientId: ingMap['turmeric'], amount: '½ tsp', isOptional: false, importance: 1 },
    ],
    instructions: [
      { step: 1, description: 'Lightly toast paneer cubes and capsicum in 1 tbsp ghee until golden. Set aside.' },
      { step: 2, description: 'In the remaining ghee, sauté onions until deep golden brown.' },
      { step: 3, description: 'Add ginger-garlic paste and turmeric, cook for 1 minute until fragrant.' },
      { step: 4, description: 'Pour in tomato puree and simmer until oil separates from the masala.' },
      { step: 5, description: 'Add garam masala, kasuri methi, paneer, and capsicum. Simmer for 5 minutes and serve.' },
    ],
  },
  {
    title: 'Hyderabadi Chicken Dum Biryani',
    description: 'Royal aromatic basmati rice layered with spiced marinated chicken, saffron, caramelized fried onions, and fresh mint leaves, slow cooked under dum seal.',
    imageUrl: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=800&q=80',
    prepTimeMinutes: 30, cookTimeMinutes: 45, difficulty: 'Hard',
    cuisine: 'Indian', mealType: 'Dinner', servings: 6,
    dietaryTags: ['gluten-free'],
    nutrition: { calories: 580, protein: 38, carbs: 65, fat: 18, fiber: 3 },
    popularity: 100,
    ingredients: [
      { ingredientId: ingMap['chicken'], amount: '600g chicken on bone', isOptional: false, importance: 3 },
      { ingredientId: ingMap['basmati rice'], amount: '2 cups aged basmati rice', isOptional: false, importance: 3 },
      { ingredientId: ingMap['yogurt'], amount: '¾ cup whisked yogurt', isOptional: false, importance: 2 },
      { ingredientId: ingMap['onion'], amount: '3 large onions, thinly sliced & fried golden', isOptional: false, importance: 2.5 },
      { ingredientId: ingMap['ginger'], amount: '2 tbsp ginger-garlic paste', isOptional: false, importance: 2 },
      { ingredientId: ingMap['garam masala'], amount: '1.5 tsp biryani masala', isOptional: false, importance: 2 },
      { ingredientId: ingMap['ghee'], amount: '3 tbsp pure ghee', isOptional: false, importance: 2 },
      { ingredientId: ingMap['mint'], amount: '½ cup chopped mint', isOptional: false, importance: 2 },
      { ingredientId: ingMap['coriander'], amount: '½ cup fresh coriander', isOptional: false, importance: 1.5 },
      { ingredientId: ingMap['chilli'], amount: '3 green chillies slit', isOptional: false, importance: 1.5 },
    ],
    instructions: [
      { step: 1, description: 'Marinate chicken with yogurt, ginger-garlic, biryani spices, half the fried onions, mint, and salt for 1 hour.' },
      { step: 2, description: 'Parboil basmati rice with whole spices until 70% cooked (about 5 mins). Drain.' },
      { step: 3, description: 'Place marinated chicken at the bottom of a heavy pot. Top with rice layer.' },
      { step: 4, description: 'Drizzle melted ghee, remaining fried onions, mint, and coriander over the rice.' },
      { step: 5, description: 'Seal pot with foil/tight lid. Cook on high for 5 mins, then low heat for 25 mins on dum.' },
    ],
  },
  {
    title: 'Creamy Dal Makhani',
    description: 'Slow-simmered whole black lentils cooked with butter, rich cream, and tomatoes. The pinnacle of Punjabi comfort dining.',
    imageUrl: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=800&q=80',
    prepTimeMinutes: 15, cookTimeMinutes: 45, difficulty: 'Medium',
    cuisine: 'Indian', mealType: 'Dinner', servings: 4,
    dietaryTags: ['vegetarian', 'gluten-free'],
    nutrition: { calories: 380, protein: 16, carbs: 42, fat: 18, fiber: 9 },
    popularity: 94,
    ingredients: [
      { ingredientId: ingMap['black lentils'], amount: '1 cup black lentils (urad dal)', isOptional: false, importance: 3 },
      { ingredientId: ingMap['butter'], amount: '3 tbsp butter', isOptional: false, importance: 2.5 },
      { ingredientId: ingMap['tomato'], amount: '3 tomatoes, pureed', isOptional: false, importance: 2 },
      { ingredientId: ingMap['garlic'], amount: '5 cloves, minced', isOptional: false, importance: 2 },
      { ingredientId: ingMap['ginger'], amount: '1 inch, julienned', isOptional: false, importance: 1.5 },
      { ingredientId: ingMap['garam masala'], amount: '1 tsp', isOptional: false, importance: 1.5 },
      { ingredientId: ingMap['kasuri methi'], amount: '1 tbsp', isOptional: true, importance: 1 },
      { ingredientId: ingMap['salt'], amount: 'to taste', isOptional: false, importance: 1 },
    ],
    instructions: [
      { step: 1, description: 'Pressure cook soaked black lentils with garlic and salt until completely soft and mashable.' },
      { step: 2, description: 'In a pot, melt butter and cook tomato puree with ginger and chilli for 10 minutes.' },
      { step: 3, description: 'Add cooked lentils and mash a portion with the back of a ladle.' },
      { step: 4, description: 'Simmer on low flame for 30 minutes, stirring occasionally as it turns velvety.' },
      { step: 5, description: 'Finish with garam masala, kasuri methi, and an extra pat of butter.' },
    ],
  },
  {
    title: 'Palak Paneer (Spinach Cottage Cheese Curry)',
    description: 'Smooth, vibrant spiced spinach puree infused with garlic, cumin, and tender paneer cubes. Nutrient-dense and deeply flavorful.',
    imageUrl: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=800&q=80',
    prepTimeMinutes: 10, cookTimeMinutes: 20, difficulty: 'Easy',
    cuisine: 'Indian', mealType: 'Dinner', servings: 4,
    dietaryTags: ['vegetarian', 'gluten-free', 'keto'],
    nutrition: { calories: 310, protein: 18, carbs: 9, fat: 22, fiber: 5 },
    popularity: 92,
    ingredients: [
      { ingredientId: ingMap['paneer'], amount: '250g paneer cubes', isOptional: false, importance: 3 },
      { ingredientId: ingMap['spinach'], amount: '4 cups fresh spinach leaves', isOptional: false, importance: 3 },
      { ingredientId: ingMap['onion'], amount: '1 onion, finely chopped', isOptional: false, importance: 2 },
      { ingredientId: ingMap['garlic'], amount: '5 cloves, minced', isOptional: false, importance: 2.5 },
      { ingredientId: ingMap['ginger'], amount: '1 inch, minced', isOptional: false, importance: 1.5 },
      { ingredientId: ingMap['cumin'], amount: '1 tsp cumin seeds', isOptional: false, importance: 1.5 },
      { ingredientId: ingMap['garam masala'], amount: '1 tsp', isOptional: false, importance: 1.5 },
      { ingredientId: ingMap['ghee'], amount: '2 tbsp ghee', isOptional: false, importance: 2 },
    ],
    instructions: [
      { step: 1, description: 'Blanch fresh spinach in boiling water for 2 minutes, then plunge into ice water to keep bright green. Puree smooth.' },
      { step: 2, description: 'Heat ghee in a pan, add cumin seeds until they sizzle.' },
      { step: 3, description: 'Add garlic, ginger, and onion. Sauté until translucent.' },
      { step: 4, description: 'Pour in spinach puree, garam masala, and salt. Simmer 5 minutes.' },
      { step: 5, description: 'Gently fold in fresh paneer cubes and warm through for 2 minutes before serving.' },
    ],
  },
  {
    title: 'Amritsari Chole (Spiced Chickpea Masala)',
    description: 'Hearty chickpeas braised in a robust, dark, spiced onion-tomato gravy with roasted cumin, ginger, and coriander. Delicious with rice or bhature.',
    imageUrl: 'https://images.unsplash.com/photo-1546833998-877b37c2e5c6?w=800&q=80',
    prepTimeMinutes: 15, cookTimeMinutes: 30, difficulty: 'Easy',
    cuisine: 'Indian', mealType: 'Lunch', servings: 4,
    dietaryTags: ['vegetarian', 'vegan', 'gluten-free'],
    nutrition: { calories: 340, protein: 15, carbs: 52, fat: 8, fiber: 12 },
    popularity: 91,
    ingredients: [
      { ingredientId: ingMap['chickpeas'], amount: '2 cups boiled chickpeas', isOptional: false, importance: 3 },
      { ingredientId: ingMap['onion'], amount: '2 onions, finely pureed', isOptional: false, importance: 2.5 },
      { ingredientId: ingMap['tomato'], amount: '2 tomatoes, pureed', isOptional: false, importance: 2.5 },
      { ingredientId: ingMap['ginger'], amount: '1 inch ginger juliennes', isOptional: false, importance: 2 },
      { ingredientId: ingMap['garlic'], amount: '4 cloves, minced', isOptional: false, importance: 2 },
      { ingredientId: ingMap['cumin'], amount: '1 tsp cumin', isOptional: false, importance: 1.5 },
      { ingredientId: ingMap['garam masala'], amount: '1 tsp', isOptional: false, importance: 2 },
      { ingredientId: ingMap['coriander'], amount: '2 tbsp fresh coriander', isOptional: true, importance: 1 },
      { ingredientId: ingMap['olive oil'], amount: '2 tbsp oil', isOptional: false, importance: 1.5 },
    ],
    instructions: [
      { step: 1, description: 'Heat oil in a pan, add cumin seeds and allow them to crackle.' },
      { step: 2, description: 'Add onion paste and sauté until golden brown and aromatic.' },
      { step: 3, description: 'Add ginger-garlic paste and tomato puree. Cook for 8 minutes until oil separates.' },
      { step: 4, description: 'Add boiled chickpeas, garam masala, salt, and 1 cup water. Lightly mash some chickpeas.' },
      { step: 5, description: 'Simmer for 15 minutes. Garnish with fresh ginger slivers and chopped coriander.' },
    ],
  },
  {
    title: 'Aloo Gobi Matar (Homestyle Spiced Potatoes & Cauliflower)',
    description: 'Classic North Indian sabzi of tender potato cubes, cauliflower florets, and sweet green peas spiced with turmeric, cumin, and fresh ginger.',
    imageUrl: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=800&q=80',
    prepTimeMinutes: 10, cookTimeMinutes: 20, difficulty: 'Easy',
    cuisine: 'Indian', mealType: 'Lunch', servings: 3,
    dietaryTags: ['vegetarian', 'vegan', 'gluten-free'],
    nutrition: { calories: 230, protein: 6, carbs: 36, fat: 8, fiber: 7 },
    popularity: 88,
    ingredients: [
      { ingredientId: ingMap['cauliflower'], amount: '2 cups cauliflower florets', isOptional: false, importance: 3 },
      { ingredientId: ingMap['potato'], amount: '2 medium potatoes, diced', isOptional: false, importance: 3 },
      { ingredientId: ingMap['green peas'], amount: '½ cup green peas', isOptional: false, importance: 2 },
      { ingredientId: ingMap['turmeric'], amount: '1 tsp turmeric powder', isOptional: false, importance: 2 },
      { ingredientId: ingMap['cumin'], amount: '1 tsp cumin seeds', isOptional: false, importance: 1.5 },
      { ingredientId: ingMap['ginger'], amount: '1 inch, finely grated', isOptional: false, importance: 2 },
      { ingredientId: ingMap['chilli'], amount: '1 green chilli, slit', isOptional: false, importance: 1.5 },
      { ingredientId: ingMap['coriander'], amount: '2 tbsp fresh coriander', isOptional: true, importance: 1 },
      { ingredientId: ingMap['olive oil'], amount: '2 tbsp cooking oil', isOptional: false, importance: 1.5 },
    ],
    instructions: [
      { step: 1, description: 'Heat oil in a kadai / pan, add cumin seeds and green chillies.' },
      { step: 2, description: 'Add diced potatoes and cauliflower florets. Stir-fry on medium heat for 5 minutes.' },
      { step: 3, description: 'Add turmeric, ginger, salt, and green peas. Toss well to coat.' },
      { step: 4, description: 'Cover with lid and cook on low heat for 12-15 minutes until veggies are tender.' },
      { step: 5, description: 'Uncover, sprinkle chopped coriander, and serve with hot chapatis.' },
    ],
  },
  {
    title: 'South Indian Sambar',
    description: 'Traditional lentil and mixed vegetable stew tempered with mustard seeds, curry leaves, and tangy tamarind broth. Perfect with rice or idli.',
    imageUrl: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=800&q=80',
    prepTimeMinutes: 15, cookTimeMinutes: 25, difficulty: 'Easy',
    cuisine: 'Indian', mealType: 'Lunch', servings: 4,
    dietaryTags: ['vegetarian', 'vegan', 'gluten-free'],
    nutrition: { calories: 210, protein: 9, carbs: 38, fat: 3, fiber: 8 },
    popularity: 89,
    ingredients: [
      { ingredientId: ingMap['toor dal'], amount: '1 cup toor dal (pigeon peas)', isOptional: false, importance: 3 },
      { ingredientId: ingMap['tomato'], amount: '2 tomatoes, chopped', isOptional: false, importance: 2 },
      { ingredientId: ingMap['onion'], amount: '1 onion or shallots', isOptional: false, importance: 2 },
      { ingredientId: ingMap['carrot'], amount: '1 carrot, sliced', isOptional: true, importance: 1.5 },
      { ingredientId: ingMap['tamarind'], amount: '1 tbsp tamarind extract', isOptional: false, importance: 2.5 },
      { ingredientId: ingMap['mustard seeds'], amount: '1 tsp mustard seeds', isOptional: false, importance: 2 },
      { ingredientId: ingMap['curry leaves'], amount: '1 sprig fresh curry leaves', isOptional: false, importance: 2 },
      { ingredientId: ingMap['turmeric'], amount: '½ tsp turmeric', isOptional: false, importance: 1 },
      { ingredientId: ingMap['ghee'], amount: '1 tbsp ghee or oil', isOptional: false, importance: 1.5 },
    ],
    instructions: [
      { step: 1, description: 'Boil toor dal with turmeric and tomatoes until soft and mashable.' },
      { step: 2, description: 'Cook carrots and onions in tamarind water with salt until tender.' },
      { step: 3, description: 'Mix the mashed dal into the tamarind vegetable broth and simmer 10 mins.' },
      { step: 4, description: 'Tadka: Heat ghee in a small pan, add mustard seeds and curry leaves until they crackle.' },
      { step: 5, description: 'Pour aromatic tadka over the bubbling sambar and stir well.' },
    ],
  },
  {
    title: 'Dhaba Style Egg Curry',
    description: 'Golden pan-fried boiled eggs steeped in a spicy, rustic onion, garlic, and tomato masala gravy. A classic highway dhaba favorite.',
    imageUrl: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=800&q=80',
    prepTimeMinutes: 10, cookTimeMinutes: 20, difficulty: 'Easy',
    cuisine: 'Indian', mealType: 'Dinner', servings: 3,
    dietaryTags: ['gluten-free'],
    nutrition: { calories: 290, protein: 18, carbs: 12, fat: 19, fiber: 2 },
    popularity: 90,
    ingredients: [
      { ingredientId: ingMap['egg'], amount: '4 boiled eggs', isOptional: false, importance: 3 },
      { ingredientId: ingMap['onion'], amount: '2 onions, finely diced', isOptional: false, importance: 2.5 },
      { ingredientId: ingMap['tomato'], amount: '2 tomatoes, chopped', isOptional: false, importance: 2.5 },
      { ingredientId: ingMap['ginger'], amount: '1 inch, minced', isOptional: false, importance: 2 },
      { ingredientId: ingMap['garlic'], amount: '4 cloves, minced', isOptional: false, importance: 2 },
      { ingredientId: ingMap['turmeric'], amount: '½ tsp', isOptional: false, importance: 1 },
      { ingredientId: ingMap['garam masala'], amount: '1 tsp', isOptional: false, importance: 2 },
      { ingredientId: ingMap['chilli'], amount: '1 green chilli', isOptional: false, importance: 1.5 },
      { ingredientId: ingMap['olive oil'], amount: '2 tbsp oil', isOptional: false, importance: 1.5 },
    ],
    instructions: [
      { step: 1, description: 'Prick boiled eggs with a fork and fry with a pinch of turmeric and chilli until blistered and golden.' },
      { step: 2, description: 'In the same pan, fry onions until deep brown.' },
      { step: 3, description: 'Add ginger-garlic paste, chillies, and tomatoes. Sauté until mushy and oil releases.' },
      { step: 4, description: 'Add garam masala, ½ cup water, and simmer into a thick gravy.' },
      { step: 5, description: 'Drop the fried eggs in and simmer for 5 minutes. Serve with hot roti or rice.' },
    ],
  },
  {
    title: 'Goan Coconut Fish Curry',
    description: 'Fresh fish fillets poached gently in a spiced coconut milk gravy infused with mustard seeds, curry leaves, and green chillies.',
    imageUrl: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=800&q=80',
    prepTimeMinutes: 15, cookTimeMinutes: 20, difficulty: 'Medium',
    cuisine: 'Indian', mealType: 'Dinner', servings: 4,
    dietaryTags: ['gluten-free', 'dairy-free'],
    nutrition: { calories: 370, protein: 28, carbs: 8, fat: 26, fiber: 2 },
    popularity: 93,
    ingredients: [
      { ingredientId: ingMap['fish'], amount: '400g white fish fillets', isOptional: false, importance: 3 },
      { ingredientId: ingMap['coconut milk'], amount: '1 cup thick coconut milk', isOptional: false, importance: 3 },
      { ingredientId: ingMap['mustard seeds'], amount: '1 tsp mustard seeds', isOptional: false, importance: 2 },
      { ingredientId: ingMap['curry leaves'], amount: '1 sprig curry leaves', isOptional: false, importance: 2 },
      { ingredientId: ingMap['ginger'], amount: '1 inch, grated', isOptional: false, importance: 1.5 },
      { ingredientId: ingMap['turmeric'], amount: '1 tsp turmeric', isOptional: false, importance: 1.5 },
      { ingredientId: ingMap['chilli'], amount: '2 green chillies, slit', isOptional: false, importance: 2 },
      { ingredientId: ingMap['olive oil'], amount: '2 tbsp oil', isOptional: false, importance: 1.5 },
    ],
    instructions: [
      { step: 1, description: 'Rub fish fillets with turmeric and salt. Let rest for 10 minutes.' },
      { step: 2, description: 'Heat oil in a pan, add mustard seeds, curry leaves, ginger, and green chillies.' },
      { step: 3, description: 'Pour in coconut milk and ½ cup water. Bring to a gentle simmer.' },
      { step: 4, description: 'Slide fish fillets into the coconut gravy. Simmer on low heat for 7-8 minutes.' },
      { step: 5, description: 'Serve hot with steamed basmati rice.' },
    ],
  },
  {
    title: 'Punjabi Rajma Masala (Red Kidney Bean Curry)',
    description: 'Slow-cooked red kidney beans in a luscious spiced onion-tomato gravy. The ultimate soul food of North India.',
    imageUrl: 'https://images.unsplash.com/photo-1546833998-877b37c2e5c6?w=800&q=80',
    prepTimeMinutes: 15, cookTimeMinutes: 35, difficulty: 'Easy',
    cuisine: 'Indian', mealType: 'Lunch', servings: 4,
    dietaryTags: ['vegetarian', 'vegan', 'gluten-free'],
    nutrition: { calories: 320, protein: 16, carbs: 48, fat: 6, fiber: 11 },
    popularity: 95,
    ingredients: [
      { ingredientId: ingMap['kidney beans'], amount: '2 cups boiled kidney beans (rajma)', isOptional: false, importance: 3 },
      { ingredientId: ingMap['onion'], amount: '2 onions, finely chopped', isOptional: false, importance: 2.5 },
      { ingredientId: ingMap['tomato'], amount: '3 tomatoes, pureed', isOptional: false, importance: 2.5 },
      { ingredientId: ingMap['ginger'], amount: '1 inch ginger paste', isOptional: false, importance: 2 },
      { ingredientId: ingMap['garlic'], amount: '5 cloves garlic', isOptional: false, importance: 2 },
      { ingredientId: ingMap['cumin'], amount: '1 tsp cumin seeds', isOptional: false, importance: 1.5 },
      { ingredientId: ingMap['garam masala'], amount: '1 tsp', isOptional: false, importance: 2 },
      { ingredientId: ingMap['coriander'], amount: '2 tbsp fresh coriander', isOptional: true, importance: 1 },
      { ingredientId: ingMap['ghee'], amount: '2 tbsp ghee or oil', isOptional: false, importance: 1.5 },
    ],
    instructions: [
      { step: 1, description: 'Heat ghee in a pan, temper with cumin seeds.' },
      { step: 2, description: 'Add onions, garlic, and ginger. Sauté until dark brown.' },
      { step: 3, description: 'Add tomato puree and spices. Cook until oil leaves the sides.' },
      { step: 4, description: 'Add boiled kidney beans and bean broth. Lightly mash some beans for thick gravy.' },
      { step: 5, description: 'Simmer on low for 20 minutes. Garnish with coriander and serve with steamed rice.' },
    ],
  },
  {
    title: 'Tadka Dal & Jeera Rice Combo',
    description: 'Golden yellow lentils tempered with sizzling garlic, cumin, and dried red chilli, paired with fragrant cumin-infused basmati rice.',
    imageUrl: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=800&q=80',
    prepTimeMinutes: 10, cookTimeMinutes: 20, difficulty: 'Easy',
    cuisine: 'Indian', mealType: 'Lunch', servings: 3,
    dietaryTags: ['vegetarian', 'gluten-free'],
    nutrition: { calories: 360, protein: 14, carbs: 62, fat: 6, fiber: 7 },
    popularity: 97,
    ingredients: [
      { ingredientId: ingMap['moong dal'], amount: '1 cup moong or toor dal', isOptional: false, importance: 3 },
      { ingredientId: ingMap['basmati rice'], amount: '1.5 cups basmati rice', isOptional: false, importance: 3 },
      { ingredientId: ingMap['cumin'], amount: '2 tsp cumin seeds', isOptional: false, importance: 2.5 },
      { ingredientId: ingMap['garlic'], amount: '6 cloves, sliced', isOptional: false, importance: 2.5 },
      { ingredientId: ingMap['ghee'], amount: '2 tbsp ghee', isOptional: false, importance: 2 },
      { ingredientId: ingMap['turmeric'], amount: '½ tsp turmeric', isOptional: false, importance: 1.5 },
      { ingredientId: ingMap['coriander'], amount: '2 tbsp fresh coriander', isOptional: true, importance: 1 },
    ],
    instructions: [
      { step: 1, description: 'Cook dal with turmeric, salt, and water until soft and creamy.' },
      { step: 2, description: 'In a pot, heat 1 tbsp ghee, fry 1 tsp cumin seeds, add basmati rice and 3 cups water. Cook covered until fluffy.' },
      { step: 3, description: 'For Dal Tadka: Heat 1 tbsp ghee in a ladle, fry sliced garlic and 1 tsp cumin seeds until golden brown.' },
      { step: 4, description: 'Pour the sizzling garlic tadka over the dal and cover immediately to trap the smoky aroma.' },
      { step: 5, description: 'Serve piping hot dal over fragrant jeera rice.' },
    ],
  },
];

const seedDatabase = async () => {
  try {
    await connectDB();
    console.log('\n🌱 Starting FlavorCraft seed process...\n');

    // Clear existing data
    await Ingredient.deleteMany({});
    await Recipe.deleteMany({});
    console.log('🗑️  Cleared existing ingredients and recipes.');

    // Seed ingredients
    const createdIngredients = await Ingredient.insertMany(ingredientData);
    console.log(`✅ Created ${createdIngredients.length} ingredients.`);

    // Build ingredient name -> ID map
    const ingMap = {};
    createdIngredients.forEach((ing) => {
      ingMap[ing.name.toLowerCase()] = ing._id;
    });

    // Seed recipes
    const recipes = buildRecipes(ingMap);
    const createdRecipes = await Recipe.insertMany(recipes);
    console.log(`✅ Created ${createdRecipes.length} recipes.`);

    // Create admin user if not exists
    let admin = await User.findOne({ email: 'admin@flavorcraft.com' });
    if (!admin) {
      await User.create({
        name: 'Admin Chef',
        email: 'admin@flavorcraft.com',
        password: 'admin123456',
        role: 'admin',
      });
      console.log('✅ Created admin user: admin@flavorcraft.com / admin123456');
    } else {
      console.log('ℹ️  Admin user already exists.');
    }

    // Create demo chef user if not exists
    let chef = await User.findOne({ email: 'chef@flavorcraft.com' });
    if (!chef) {
      await User.create({
        name: 'Gordon Demo',
        email: 'chef@flavorcraft.com',
        password: 'password123',
        role: 'user',
      });
      console.log('✅ Created demo chef user: chef@flavorcraft.com / password123');
    }

    console.log('\n🎉 FlavorCraft database seeded successfully!\n');
    console.log('📋 Summary:');
    console.log(`   - ${createdIngredients.length} ingredients`);
    console.log(`   - ${createdRecipes.length} recipes`);
    console.log('   - 1 admin user (admin@flavorcraft.com)');
    console.log('\n🔐 Admin credentials:');
    console.log('   Email: admin@flavorcraft.com');
    console.log('   Password: admin123456');
    process.exit(0);
  } catch (error) {
    console.error('❌ Seed error:', error.message);
    if (error.errors) {
      Object.entries(error.errors).forEach(([key, val]) => {
        console.error(`   - ${key}: ${val.message}`);
      });
    }
    process.exit(1);
  }
};

seedDatabase();
